# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Prepare settings.xml
        run: envsubst < settings.xml.template > settings.xml
        env:
          MAVEN_USERNAME: ${{ secrets.AGENTLAB_NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.AGENTLAB_NEXUS_PASSWORD }}
      - name: Publish package
        # TODO: tests failing due to absence of test data
        run: mvn -ntp -s settings.xml clean deploy -DskipTests
